#!/bin/bash

if [ -f /tmp/my_first_directory/betty ]; then
   rm /tmp/my_first_directory/betty
   echo "The file betty has been deleted."
else
   echo "There is no such file in tmp/my_first_directory."
fi
