#!/bin/bash
mkdir -p /tmp/my_first_directory
touch /tmp/my_first_directory/betty
if [ -f /tmp/my_first_directory/betty ]; then
	echo "The file betty has been created."
else
	echo "Failed to create the file betty."
fi

		  

